### ISSUE TITLE
`remove_restore.py` overall docstring is out-of-date

### ISSUE THREAD

**Issue by alessandrofelder** [UCL/pyCascadia#38]
We should update the `remove_restore.py` docstring and add a docstring to `load_base_grid` too. We might want to expand/review the docs when we tackle this, too.

**Comment by JamieJQuinn** [comment]
Need to decide on [docstring format](https://stackoverflow.com/a/24385103). Default Sphinx (i.e. RST) is pretty simple.

Viz doc generation, do we want to go basic sphinx + readthedocs or self-host on gh-pages or other solution?
