### ISSUE TITLE
Add linting capabilities to CI

### ISSUE THREAD

**Issue by alessandrofelder** [UCL/pyCascadia#39]
It would be good to run `flake8` or similar in our CI system.

**Comment by JamieJQuinn** [comment]
Can steal my `.flake8` [config from Melvin](https://github.com/JamieJQuinn/Melvin.py/blob/master/.flake8). 

What's our feeling about automatic formatting with black?

**Comment by alessandrofelder** [comment]
Linting was implemented in the CI. We've decided against automatic formatting for now, to keep the barrier low for new contributors (no need to implement pre-commit hooks etc).
