### ISSUE TITLE
Spacing unit should be an input to `remove_restore` and default to metres

### ISSUE THREAD

**Issue by alessandrofelder** [UCL/pyCascadia#40]

**Comment by alessandrofelder** [comment]
After fighting with this for too long, I've posted a question about this on the GMT forum :)
https://forum.generic-mapping-tools.org/t/how-do-r-and-i-options-with-differing-units-interact-with-each-other-in-gmt/1690

**Comment by alessandrofelder** [comment]
We've gotten an answer to this question:
> Per the cookbook 1, the +u modifer is used to specify projected dimensions, but yours are geographic degrees. 
[...]
> There is no good workaround for this I think other than manually computing the 150m increment in degrees and give that instead.
We'll need to discuss at our next meeting how to proceed.

**Comment by JamieJQuinn** [comment]
This is no longer an issue to @Devaraj-G and seems like it's more work that it's worth. Closing.
