### ISSUE TITLE
nodata value in input grid to remove-restore

### ISSUE THREAD

**Issue by Devaraj-G** [UCL/pyCascadia#55]
@alessandrofelder
What is the nodata value defined in the remove-resore script - 
Is it  [NODATA_VAL = 9999](https://github.com/UCL/pyCascadia/blob/main/pycascadia/remove_restore.py#L45)?

If any input grids tiff or .nc files have a different nodata value, should it be pre-processed to change that to 9999?
Does this need to be done for input grids to close_boundary also?

**Comment by JamieJQuinn** [comment]
From Slack: 

> There's no defined nodata values in remove-restore used to filter any input grids. The NODATA_VAL = 9999 you've noticed is used internally to facilitate the windowing algorithm. Any nodata values in the input data are extracted (and filtered) from the geotiff inputs, since the geotiff format has a field containing nodata values, but we haven't encountered a netcdf file containing nodata values yet so filtering that format isn't implemented but it certainly can be if you have an example netcdf file!
