### ISSUE TITLE
Remove-restore should have an option to take a text file containing a list of input grids

### ISSUE THREAD

**Issue by JamieJQuinn** [UCL/pyCascadia#56]
Since remove-restore is being used to combine potentially thousands of files, there should be an option to provide a text file containing the list of input files, rather than listing them explicitly via command line arguments.

**Comment by Devaraj-G** [comment]
I run:
`remove-restore  --base ../Work/Data_Code/IAAC2/2021_07_06_gebco_2020/gebco_2020_n60.0_s37.0_w-140.0_e-119.0.nc  --output ../Work/Data_Code/IAAC2/temp/merged_dem_30m.nc  --spacing 0.000277778  --region_of_interest -137.250000000 -121.250000000   39.750000000   56.250000000  --input_txt ../Work/Data_Code/IAAC2/temp/filelist.txt`

And it outputs on terminal:
_usage: remove-restore [-h] --base BASE [--input_txt INPUT_TXT] [--spacing SPACING] [--diff_threshold DIFF_THRESHOLD] [--plot] --output OUTPUT [--window_width WINDOW_WIDTH]
                      [--region_of_interest xmin xmax ymin ymax]
                      filenames [filenames ...]
remove-restore: error: the following arguments are required: filenames_

[filelist.txt](https://github.com/UCL/pyCascadia/files/6776565/filelist.txt)

**Comment by JamieJQuinn** [comment]
The original issue has been implemented in #57 and the subsequent issue with filenames has been fixed in #62. Closing.
