### ISSUE TITLE
Non-rectangular update grid

### ISSUE THREAD

**Issue by Devaraj-G** [UCL/pyCascadia#61]
Can remove-restore handle non-rectangular update grids? 

Instead of feeding individual DEM files to remove-restore, one can mosaic them using [gdal_merge.py](https://gdal.org/programs/gdal_merge.html) and feed it as one update grid. This is very suitable for NONAA100 (98 files) + NONAA10 (7008 files).

e.g. ![Spead of NONNA100 and NONNA10](https://user-images.githubusercontent.com/36169767/124720635-4117b980-df00-11eb-8690-69ded8e3374b.png)

**Comment by JamieJQuinn** [comment]
Yes, it breaks an input grid into a list of points before applying the remove-restore algorithm so it should handle any shape. One of the NOAA grids I used to test was non-rectangular.
