### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by JamieJQuinn** [UCL/pyCascadia#71]
Which licence should be used?

Seems like the [Mozilla public licence](https://opensource.org/licenses/MPL-2.0) is best suited to this kind of library, allowing users to use the lib without being required to release their code under the same licence (as would be the case with GPL). It is not entirely without permissions since it still requires the library (and any modifications) to remain under the MPL, and thus remain publicly available. To me this best strikes the balance between encouraging the library's use, even in proprietary code, while ensuring it (and modifications) remain publicly available.

**Comment by alessandrofelder** [comment]
I have no strong opinion as long as it's open. I'd happy with MPL as well as with MIT.
